export const PERM = {
  // Principal
  IAM_ME_READ: "IAM_ME_READ",
  IAM_USER_READ: "IAM_USER_READ",
  IAM_USER_CREATE: "IAM_USER_CREATE",
  IAM_USER_UPDATE: "IAM_USER_UPDATE",
  IAM_USER_RESET_PASSWORD: "IAM_USER_RESET_PASSWORD",
  IAM_PERMISSION_CREATE: "IAM_PERMISSION_CREATE",
  // Permission catalog / metadata / sync (enterprise)
  IAM_PERMISSION_MANAGE: "IAM_PERMISSION_MANAGE",
  IAM_ROLE_READ: "IAM_ROLE_READ",
  IAM_PERMISSION_READ: "IAM_PERMISSION_READ",
  IAM_AUDIT_READ: "IAM_AUDIT_READ",
  IAM_ROLE_CREATE: "IAM_ROLE_CREATE",
  IAM_ROLE_UPDATE: "IAM_ROLE_UPDATE",

  // Policy Governance
  GOV_POLICY_READ: "GOV_POLICY_READ",
  GOV_POLICY_GLOBAL_DRAFT: "GOV_POLICY_GLOBAL_DRAFT",
  GOV_POLICY_BRANCH_OVERRIDE_DRAFT: "GOV_POLICY_BRANCH_OVERRIDE_DRAFT",
  GOV_POLICY_SUBMIT: "GOV_POLICY_SUBMIT",
  GOV_POLICY_APPROVE: "GOV_POLICY_APPROVE",
  GOV_POLICY_AUDIT_READ: "GOV_POLICY_AUDIT_READ",

  // Branch Management
  BRANCH_READ: "BRANCH_READ",
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_DELETE: "BRANCH_DELETE",

  // Facility Management
  FACILITY_CATALOG_READ: "FACILITY_CATALOG_READ",
  BRANCH_FACILITY_READ: "BRANCH_FACILITY_READ",
  BRANCH_FACILITY_UPDATE: "BRANCH_FACILITY_UPDATE",
  DEPARTMENT_READ: "DEPARTMENT_READ",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_ASSIGN_DOCTORS: "DEPARTMENT_ASSIGN_DOCTORS",
  DEPARTMENT_SPECIALTY_READ: "DEPARTMENT_SPECIALTY_READ",
  DEPARTMENT_SPECIALTY_UPDATE: "DEPARTMENT_SPECIALTY_UPDATE",
  STAFF_READ: "STAFF_READ",

  FACILITY_CATALOG_CREATE: "FACILITY_CATALOG_CREATE",

  SPECIALTY_READ: "SPECIALTY_READ",
  SPECIALTY_CREATE: "SPECIALTY_CREATE",
  SPECIALTY_UPDATE: "SPECIALTY_UPDATE",

  // Infrastructure / Setup Studio
  INFRA_LOCATION_READ: "INFRA_LOCATION_READ",
  INFRA_LOCATION_CREATE: "INFRA_LOCATION_CREATE",
  INFRA_LOCATION_REVISE: "INFRA_LOCATION_REVISE",
  INFRA_LOCATION_RETIRE: "INFRA_LOCATION_RETIRE",
  INFRA_LOCATION_UPDATE: "INFRA_LOCATION_UPDATE",

  INFRA_UNITTYPE_READ: "INFRA_UNITTYPE_READ",
  INFRA_UNITTYPE_UPDATE: "INFRA_UNITTYPE_UPDATE",

  INFRA_UNIT_READ: "INFRA_UNIT_READ",
  INFRA_UNIT_CREATE: "INFRA_UNIT_CREATE",
  INFRA_UNIT_UPDATE: "INFRA_UNIT_UPDATE",
  INFRA_UNIT_DELETE: "INFRA_UNIT_DELETE",

  INFRA_ROOM_READ: "INFRA_ROOM_READ",
  INFRA_ROOM_CREATE: "INFRA_ROOM_CREATE",
  INFRA_ROOM_UPDATE: "INFRA_ROOM_UPDATE",

  INFRA_RESOURCE_READ: "INFRA_RESOURCE_READ",
  INFRA_RESOURCE_CREATE: "INFRA_RESOURCE_CREATE",
  INFRA_RESOURCE_UPDATE: "INFRA_RESOURCE_UPDATE",
  INFRA_RESOURCE_STATE_UPDATE: "INFRA_RESOURCE_STATE_UPDATE",

  INFRA_EQUIPMENT_READ: "INFRA_EQUIPMENT_READ",
  INFRA_EQUIPMENT_CREATE: "INFRA_EQUIPMENT_CREATE",
  INFRA_EQUIPMENT_UPDATE: "INFRA_EQUIPMENT_UPDATE",

  INFRA_SERVICE_READ: "INFRA_SERVICE_READ",
  INFRA_SERVICE_CREATE: "INFRA_SERVICE_CREATE",
  INFRA_SERVICE_UPDATE: "INFRA_SERVICE_UPDATE",

  // Advanced service master (catalogues, packages, order sets)
  INFRA_SERVICE_CATALOGUE_CREATE: "INFRA_SERVICE_CATALOGUE_CREATE",
  INFRA_SERVICE_CATALOGUE_READ: "INFRA_SERVICE_CATALOGUE_READ",
  INFRA_SERVICE_CATALOGUE_UPDATE: "INFRA_SERVICE_CATALOGUE_UPDATE",
  INFRA_SERVICE_CATALOGUE_PUBLISH: "INFRA_SERVICE_CATALOGUE_PUBLISH",

  INFRA_SERVICE_PACKAGE_CREATE: "INFRA_SERVICE_PACKAGE_CREATE",
  INFRA_SERVICE_PACKAGE_READ: "INFRA_SERVICE_PACKAGE_READ",
  INFRA_SERVICE_PACKAGE_UPDATE: "INFRA_SERVICE_PACKAGE_UPDATE",
  INFRA_SERVICE_PACKAGE_PUBLISH: "INFRA_SERVICE_PACKAGE_PUBLISH",

  INFRA_ORDER_SET_CREATE: "INFRA_ORDER_SET_CREATE",
  INFRA_ORDER_SET_READ: "INFRA_ORDER_SET_READ",
  INFRA_ORDER_SET_UPDATE: "INFRA_ORDER_SET_UPDATE",
  INFRA_ORDER_SET_PUBLISH: "INFRA_ORDER_SET_PUBLISH",

  // Service Library (standard code sets + mappings)
  INFRA_CODE_SET_CREATE: "INFRA_CODE_SET_CREATE",
  INFRA_CODE_SET_READ: "INFRA_CODE_SET_READ",
  INFRA_CODE_SET_UPDATE: "INFRA_CODE_SET_UPDATE",

  INFRA_CHARGE_MASTER_READ: "INFRA_CHARGE_MASTER_READ",
  INFRA_CHARGE_MASTER_CREATE: "INFRA_CHARGE_MASTER_CREATE",
  INFRA_CHARGE_MASTER_UPDATE: "INFRA_CHARGE_MASTER_UPDATE",

  INFRA_SERVICE_MAPPING_UPDATE: "INFRA_SERVICE_MAPPING_UPDATE",
  INFRA_FIXIT_READ: "INFRA_FIXIT_READ",
  INFRA_FIXIT_UPDATE: "INFRA_FIXIT_UPDATE",

  INFRA_IMPORT_VALIDATE: "INFRA_IMPORT_VALIDATE",
  INFRA_IMPORT_COMMIT: "INFRA_IMPORT_COMMIT",

  INFRA_SCHED_READ: "INFRA_SCHED_READ",
  INFRA_SCHED_CREATE: "INFRA_SCHED_CREATE",
  INFRA_SCHED_CANCEL: "INFRA_SCHED_CANCEL",

  INFRA_GOLIVE_READ: "INFRA_GOLIVE_READ",
  INFRA_GOLIVE_RUN: "INFRA_GOLIVE_RUN",

  // ✅ Billing Setup (Tariffs) — NEW (used by billing.controller)
  INFRA_TARIFF_PLAN_READ: "INFRA_TARIFF_PLAN_READ",
  INFRA_TARIFF_PLAN_CREATE: "INFRA_TARIFF_PLAN_CREATE",
  INFRA_TARIFF_PLAN_UPDATE: "INFRA_TARIFF_PLAN_UPDATE",

  INFRA_TARIFF_RATE_READ: "INFRA_TARIFF_RATE_READ",
  INFRA_TARIFF_RATE_UPDATE: "INFRA_TARIFF_RATE_UPDATE",

  // Tax Codes (GST/Tax setup)
  INFRA_TAX_CODE_READ: "INFRA_TAX_CODE_READ",
  INFRA_TAX_CODE_CREATE: "INFRA_TAX_CODE_CREATE",
  INFRA_TAX_CODE_UPDATE: "INFRA_TAX_CODE_UPDATE",

  // Service Availability
  INFRA_SERVICE_AVAILABILITY_READ: "INFRA_SERVICE_AVAILABILITY_READ",
  INFRA_SERVICE_AVAILABILITY_UPDATE: "INFRA_SERVICE_AVAILABILITY_UPDATE",

  // Diagnostics configuration (Infrastructure)
  INFRA_DIAGNOSTICS_READ: "INFRA_DIAGNOSTICS_READ",
  INFRA_DIAGNOSTICS_CREATE: "INFRA_DIAGNOSTICS_CREATE",
  INFRA_DIAGNOSTICS_UPDATE: "INFRA_DIAGNOSTICS_UPDATE",
  INFRA_DIAGNOSTICS_DELETE: "INFRA_DIAGNOSTICS_DELETE",

  // Operation Theatre
  OT_SUITE_CREATE: "ot.suite.create",
  OT_SUITE_READ: "ot.suite.read",
  OT_SUITE_UPDATE: "ot.suite.update",
  OT_SUITE_DELETE: "ot.suite.delete",

  OT_SPACE_CREATE: "ot.space.create",
  OT_SPACE_UPDATE: "ot.space.update",
  OT_SPACE_DELETE: "ot.space.delete",

  OT_TABLE_CREATE: "ot.table.create",
  OT_TABLE_UPDATE: "ot.table.update",
  OT_TABLE_DELETE: "ot.table.delete",

  OT_EQUIPMENT_CREATE: "ot.equipment.create",
  OT_EQUIPMENT_UPDATE: "ot.equipment.update",
  OT_EQUIPMENT_DELETE: "ot.equipment.delete",
} as const;

export const ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  // Enterprise-level admin (GLOBAL). Can manage branches + enterprise users,
  // but should NOT have system-level RBAC design or governance policy controls by default.
  CORPORATE_ADMIN: "CORPORATE_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  IT_ADMIN: "IT_ADMIN",
} as const;
