export const PERM = {
  // Principal
  IAM_ME_READ: "IAM_ME_READ",
  IAM_USER_READ: "IAM_USER_READ",
  IAM_USER_CREATE: "IAM_USER_CREATE",
  IAM_USER_UPDATE: "IAM_USER_UPDATE",
  IAM_USER_RESET_PASSWORD: "IAM_USER_RESET_PASSWORD",
  IAM_PERMISSION_CREATE: "IAM_PERMISSION_CREATE",
  // Permission catalog / metadata / sync (enterprise)
  IAM_PERMISSION_MANAGE: "IAM_PERMISSION_MANAGE",
  IAM_ROLE_READ: "IAM_ROLE_READ",
  IAM_PERMISSION_READ: "IAM_PERMISSION_READ",
  IAM_AUDIT_READ: "IAM_AUDIT_READ",
  IAM_ROLE_CREATE: "IAM_ROLE_CREATE",
  IAM_ROLE_UPDATE: "IAM_ROLE_UPDATE",

  // Policy Governance
  GOV_POLICY_READ: "GOV_POLICY_READ",
  GOV_POLICY_GLOBAL_DRAFT: "GOV_POLICY_GLOBAL_DRAFT",
  GOV_POLICY_BRANCH_OVERRIDE_DRAFT: "GOV_POLICY_BRANCH_OVERRIDE_DRAFT",
  GOV_POLICY_SUBMIT: "GOV_POLICY_SUBMIT",
  GOV_POLICY_APPROVE: "GOV_POLICY_APPROVE",
  GOV_POLICY_AUDIT_READ: "GOV_POLICY_AUDIT_READ",

  // Branch Management
  BRANCH_READ: "BRANCH_READ",
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_DELETE: "BRANCH_DELETE",

  // Facility Management
  FACILITY_CATALOG_READ: "FACILITY_CATALOG_READ",
  BRANCH_FACILITY_READ: "BRANCH_FACILITY_READ",
  BRANCH_FACILITY_UPDATE: "BRANCH_FACILITY_UPDATE",
  DEPARTMENT_READ: "DEPARTMENT_READ",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_ASSIGN_DOCTORS: "DEPARTMENT_ASSIGN_DOCTORS",
  DEPARTMENT_SPECIALTY_READ: "DEPARTMENT_SPECIALTY_READ",
  DEPARTMENT_SPECIALTY_UPDATE: "DEPARTMENT_SPECIALTY_UPDATE",
  STAFF_READ: "STAFF_READ",

  // Human Resource / Staff Management (HR)
  STAFF_CREATE: "STAFF_CREATE",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_ASSIGNMENT_CREATE: "STAFF_ASSIGNMENT_CREATE",
  STAFF_ASSIGNMENT_UPDATE: "STAFF_ASSIGNMENT_UPDATE",
  STAFF_ASSIGNMENT_END: "STAFF_ASSIGNMENT_END",
  STAFF_PROVISION_USER_PREVIEW: "STAFF_PROVISION_USER_PREVIEW",
  STAFF_PROVISION_USER: "STAFF_PROVISION_USER",
  STAFF_CREDENTIAL_CREATE: "STAFF_CREDENTIAL_CREATE",
  STAFF_CREDENTIAL_UPDATE: "STAFF_CREDENTIAL_UPDATE",
  STAFF_DEDUPE_PREVIEW: "STAFF_DEDUPE_PREVIEW",
  STAFF_MERGE_PREVIEW: "STAFF_MERGE_PREVIEW",
  STAFF_MERGE: "STAFF_MERGE",
  STAFF_SUSPEND: "STAFF_SUSPEND",
  STAFF_REACTIVATE: "STAFF_REACTIVATE",
  STAFF_OFFBOARD: "STAFF_OFFBOARD",
  STAFF_IDENTIFIER_CREATE: "STAFF_IDENTIFIER_CREATE",
  STAFF_IDENTIFIER_DELETE: "STAFF_IDENTIFIER_DELETE",
  STAFF_AUDIT_READ: "STAFF_AUDIT_READ",
  STAFF_REPORTS_READ: "STAFF_REPORTS_READ",

  FACILITY_CATALOG_CREATE: "FACILITY_CATALOG_CREATE",

  SPECIALTY_READ: "SPECIALTY_READ",
  SPECIALTY_CREATE: "SPECIALTY_CREATE",
  SPECIALTY_UPDATE: "SPECIALTY_UPDATE",

  // Infrastructure / Setup Studio
  INFRA_LOCATION_READ: "INFRA_LOCATION_READ",
  INFRA_LOCATION_CREATE: "INFRA_LOCATION_CREATE",
  INFRA_LOCATION_REVISE: "INFRA_LOCATION_REVISE",
  INFRA_LOCATION_RETIRE: "INFRA_LOCATION_RETIRE",
  INFRA_LOCATION_UPDATE: "INFRA_LOCATION_UPDATE",

  INFRA_UNITTYPE_READ: "INFRA_UNITTYPE_READ",
  INFRA_UNITTYPE_UPDATE: "INFRA_UNITTYPE_UPDATE",

  INFRA_UNIT_READ: "INFRA_UNIT_READ",
  INFRA_UNIT_CREATE: "INFRA_UNIT_CREATE",
  INFRA_UNIT_UPDATE: "INFRA_UNIT_UPDATE",
  INFRA_UNIT_DELETE: "INFRA_UNIT_DELETE",

  INFRA_ROOM_READ: "INFRA_ROOM_READ",
  INFRA_ROOM_CREATE: "INFRA_ROOM_CREATE",
  INFRA_ROOM_UPDATE: "INFRA_ROOM_UPDATE",

  INFRA_RESOURCE_READ: "INFRA_RESOURCE_READ",
  INFRA_RESOURCE_CREATE: "INFRA_RESOURCE_CREATE",
  INFRA_RESOURCE_UPDATE: "INFRA_RESOURCE_UPDATE",
  INFRA_RESOURCE_STATE_UPDATE: "INFRA_RESOURCE_STATE_UPDATE",

  INFRA_EQUIPMENT_READ: "INFRA_EQUIPMENT_READ",
  INFRA_EQUIPMENT_CREATE: "INFRA_EQUIPMENT_CREATE",
  INFRA_EQUIPMENT_UPDATE: "INFRA_EQUIPMENT_UPDATE",

  INFRA_SERVICE_READ: "INFRA_SERVICE_READ",
  INFRA_SERVICE_CREATE: "INFRA_SERVICE_CREATE",
  INFRA_SERVICE_UPDATE: "INFRA_SERVICE_UPDATE",

  // Advanced service master (catalogues, packages, order sets)
  INFRA_SERVICE_CATALOGUE_CREATE: "INFRA_SERVICE_CATALOGUE_CREATE",
  INFRA_SERVICE_CATALOGUE_READ: "INFRA_SERVICE_CATALOGUE_READ",
  INFRA_SERVICE_CATALOGUE_UPDATE: "INFRA_SERVICE_CATALOGUE_UPDATE",
  INFRA_SERVICE_CATALOGUE_PUBLISH: "INFRA_SERVICE_CATALOGUE_PUBLISH",

  INFRA_SERVICE_PACKAGE_CREATE: "INFRA_SERVICE_PACKAGE_CREATE",
  INFRA_SERVICE_PACKAGE_READ: "INFRA_SERVICE_PACKAGE_READ",
  INFRA_SERVICE_PACKAGE_UPDATE: "INFRA_SERVICE_PACKAGE_UPDATE",
  INFRA_SERVICE_PACKAGE_PUBLISH: "INFRA_SERVICE_PACKAGE_PUBLISH",

  INFRA_ORDER_SET_CREATE: "INFRA_ORDER_SET_CREATE",
  INFRA_ORDER_SET_READ: "INFRA_ORDER_SET_READ",
  INFRA_ORDER_SET_UPDATE: "INFRA_ORDER_SET_UPDATE",
  INFRA_ORDER_SET_PUBLISH: "INFRA_ORDER_SET_PUBLISH",

  // Service Library (standard code sets + mappings)
  INFRA_CODE_SET_CREATE: "INFRA_CODE_SET_CREATE",
  INFRA_CODE_SET_READ: "INFRA_CODE_SET_READ",
  INFRA_CODE_SET_UPDATE: "INFRA_CODE_SET_UPDATE",

  INFRA_CHARGE_MASTER_READ: "INFRA_CHARGE_MASTER_READ",
  INFRA_CHARGE_MASTER_CREATE: "INFRA_CHARGE_MASTER_CREATE",
  INFRA_CHARGE_MASTER_UPDATE: "INFRA_CHARGE_MASTER_UPDATE",

  INFRA_SERVICE_MAPPING_UPDATE: "INFRA_SERVICE_MAPPING_UPDATE",
  INFRA_FIXIT_READ: "INFRA_FIXIT_READ",
  INFRA_FIXIT_UPDATE: "INFRA_FIXIT_UPDATE",

  INFRA_IMPORT_VALIDATE: "INFRA_IMPORT_VALIDATE",
  INFRA_IMPORT_COMMIT: "INFRA_IMPORT_COMMIT",

  INFRA_SCHED_READ: "INFRA_SCHED_READ",
  INFRA_SCHED_CREATE: "INFRA_SCHED_CREATE",
  INFRA_SCHED_CANCEL: "INFRA_SCHED_CANCEL",

  INFRA_GOLIVE_READ: "INFRA_GOLIVE_READ",
  INFRA_GOLIVE_RUN: "INFRA_GOLIVE_RUN",

  // ✅ Billing Setup (Tariffs) — NEW (used by billing.controller)
  INFRA_TARIFF_PLAN_READ: "INFRA_TARIFF_PLAN_READ",
  INFRA_TARIFF_PLAN_CREATE: "INFRA_TARIFF_PLAN_CREATE",
  INFRA_TARIFF_PLAN_UPDATE: "INFRA_TARIFF_PLAN_UPDATE",

  INFRA_TARIFF_RATE_READ: "INFRA_TARIFF_RATE_READ",
  INFRA_TARIFF_RATE_UPDATE: "INFRA_TARIFF_RATE_UPDATE",

  // Tax Codes (GST/Tax setup)
  INFRA_TAX_CODE_READ: "INFRA_TAX_CODE_READ",
  INFRA_TAX_CODE_CREATE: "INFRA_TAX_CODE_CREATE",
  INFRA_TAX_CODE_UPDATE: "INFRA_TAX_CODE_UPDATE",

  // Service Availability
  INFRA_SERVICE_AVAILABILITY_READ: "INFRA_SERVICE_AVAILABILITY_READ",
  INFRA_SERVICE_AVAILABILITY_UPDATE: "INFRA_SERVICE_AVAILABILITY_UPDATE",

  // Diagnostics configuration (Infrastructure)
  INFRA_DIAGNOSTICS_READ: "INFRA_DIAGNOSTICS_READ",
  INFRA_DIAGNOSTICS_CREATE: "INFRA_DIAGNOSTICS_CREATE",
  INFRA_DIAGNOSTICS_UPDATE: "INFRA_DIAGNOSTICS_UPDATE",
  INFRA_DIAGNOSTICS_DELETE: "INFRA_DIAGNOSTICS_DELETE",

  // Operation Theatre
  OT_SUITE_CREATE: "ot.suite.create",
  OT_SUITE_READ: "ot.suite.read",
  OT_SUITE_UPDATE: "ot.suite.update",
  OT_SUITE_DELETE: "ot.suite.delete",

  OT_SPACE_CREATE: "ot.space.create",
  OT_SPACE_UPDATE: "ot.space.update",
  OT_SPACE_DELETE: "ot.space.delete",

  OT_TABLE_CREATE: "ot.table.create",
  OT_TABLE_UPDATE: "ot.table.update",
  OT_TABLE_DELETE: "ot.table.delete",

  OT_EQUIPMENT_CREATE: "ot.equipment.create",
  OT_EQUIPMENT_UPDATE: "ot.equipment.update",
  OT_EQUIPMENT_DELETE: "ot.equipment.delete",

  // Pharmacy Infrastructure
  INFRA_PHARMACY_STORE_READ: "INFRA_PHARMACY_STORE_READ",
  INFRA_PHARMACY_STORE_CREATE: "INFRA_PHARMACY_STORE_CREATE",
  INFRA_PHARMACY_STORE_UPDATE: "INFRA_PHARMACY_STORE_UPDATE",

  INFRA_PHARMACY_DRUG_READ: "INFRA_PHARMACY_DRUG_READ",
  INFRA_PHARMACY_DRUG_CREATE: "INFRA_PHARMACY_DRUG_CREATE",
  INFRA_PHARMACY_DRUG_UPDATE: "INFRA_PHARMACY_DRUG_UPDATE",

  INFRA_PHARMACY_FORMULARY_READ: "INFRA_PHARMACY_FORMULARY_READ",
  INFRA_PHARMACY_FORMULARY_CREATE: "INFRA_PHARMACY_FORMULARY_CREATE",
  INFRA_PHARMACY_FORMULARY_UPDATE: "INFRA_PHARMACY_FORMULARY_UPDATE",
  INFRA_PHARMACY_FORMULARY_PUBLISH: "INFRA_PHARMACY_FORMULARY_PUBLISH",

  INFRA_PHARMACY_SUPPLIER_READ: "INFRA_PHARMACY_SUPPLIER_READ",
  INFRA_PHARMACY_SUPPLIER_CREATE: "INFRA_PHARMACY_SUPPLIER_CREATE",
  INFRA_PHARMACY_SUPPLIER_UPDATE: "INFRA_PHARMACY_SUPPLIER_UPDATE",

  INFRA_PHARMACY_INVENTORY_READ: "INFRA_PHARMACY_INVENTORY_READ",
  INFRA_PHARMACY_INVENTORY_UPDATE: "INFRA_PHARMACY_INVENTORY_UPDATE",

  INFRA_PHARMACY_NARCOTICS_READ: "INFRA_PHARMACY_NARCOTICS_READ",
  INFRA_PHARMACY_NARCOTICS_UPDATE: "INFRA_PHARMACY_NARCOTICS_UPDATE",

  INFRA_PHARMACY_INTERACTION_READ: "INFRA_PHARMACY_INTERACTION_READ",
  INFRA_PHARMACY_INTERACTION_UPDATE: "INFRA_PHARMACY_INTERACTION_UPDATE",

  INFRA_PHARMACY_SUBSTITUTION_READ: "INFRA_PHARMACY_SUBSTITUTION_READ",
  INFRA_PHARMACY_SUBSTITUTION_UPDATE: "INFRA_PHARMACY_SUBSTITUTION_UPDATE",

  INFRA_PHARMACY_CATEGORY_READ: "INFRA_PHARMACY_CATEGORY_READ",
  INFRA_PHARMACY_CATEGORY_UPDATE: "INFRA_PHARMACY_CATEGORY_UPDATE",

  // Payer Management (Financial Config)
  INFRA_PAYER_READ: "INFRA_PAYER_READ",
  INFRA_PAYER_CREATE: "INFRA_PAYER_CREATE",
  INFRA_PAYER_UPDATE: "INFRA_PAYER_UPDATE",

  INFRA_PAYER_CONTRACT_READ: "INFRA_PAYER_CONTRACT_READ",
  INFRA_PAYER_CONTRACT_CREATE: "INFRA_PAYER_CONTRACT_CREATE",
  INFRA_PAYER_CONTRACT_UPDATE: "INFRA_PAYER_CONTRACT_UPDATE",

  // Government Schemes
  INFRA_GOV_SCHEME_READ: "INFRA_GOV_SCHEME_READ",
  INFRA_GOV_SCHEME_CREATE: "INFRA_GOV_SCHEME_CREATE",
  INFRA_GOV_SCHEME_UPDATE: "INFRA_GOV_SCHEME_UPDATE",

  // Patient Pricing Tiers
  INFRA_PRICING_TIER_READ: "INFRA_PRICING_TIER_READ",
  INFRA_PRICING_TIER_CREATE: "INFRA_PRICING_TIER_CREATE",
  INFRA_PRICING_TIER_UPDATE: "INFRA_PRICING_TIER_UPDATE",

  // Service Price History
  INFRA_PRICE_HISTORY_READ: "INFRA_PRICE_HISTORY_READ",

  // ========== Insurance Claims Transaction Layer ==========

  // Insurance Policies
  BILLING_POLICY_READ: "BILLING_POLICY_READ",
  BILLING_POLICY_CREATE: "BILLING_POLICY_CREATE",
  BILLING_POLICY_UPDATE: "BILLING_POLICY_UPDATE",

  // Insurance Cases
  BILLING_CASE_READ: "BILLING_CASE_READ",
  BILLING_CASE_CREATE: "BILLING_CASE_CREATE",
  BILLING_CASE_UPDATE: "BILLING_CASE_UPDATE",

  // Pre-authorization
  BILLING_PREAUTH_READ: "BILLING_PREAUTH_READ",
  BILLING_PREAUTH_CREATE: "BILLING_PREAUTH_CREATE",
  BILLING_PREAUTH_UPDATE: "BILLING_PREAUTH_UPDATE",
  BILLING_PREAUTH_APPROVE: "BILLING_PREAUTH_APPROVE",

  // Claims
  BILLING_CLAIM_READ: "BILLING_CLAIM_READ",
  BILLING_CLAIM_CREATE: "BILLING_CLAIM_CREATE",
  BILLING_CLAIM_UPDATE: "BILLING_CLAIM_UPDATE",
  BILLING_CLAIM_APPROVE: "BILLING_CLAIM_APPROVE",

  // Insurance Documents
  BILLING_DOCUMENT_READ: "BILLING_DOCUMENT_READ",
  BILLING_DOCUMENT_CREATE: "BILLING_DOCUMENT_CREATE",
  BILLING_DOCUMENT_UPDATE: "BILLING_DOCUMENT_UPDATE",

  // Payer Integration
  BILLING_INTEGRATION_READ: "BILLING_INTEGRATION_READ",
  BILLING_INTEGRATION_CREATE: "BILLING_INTEGRATION_CREATE",
  BILLING_INTEGRATION_UPDATE: "BILLING_INTEGRATION_UPDATE",

  // Payment Reconciliation
  BILLING_RECONCILIATION_READ: "BILLING_RECONCILIATION_READ",
  BILLING_RECONCILIATION_CREATE: "BILLING_RECONCILIATION_CREATE",
  BILLING_RECONCILIATION_UPDATE: "BILLING_RECONCILIATION_UPDATE",

  // Dashboard
  BILLING_DASHBOARD_READ: "BILLING_DASHBOARD_READ",

  // ========== Compliance Infrastructure ==========

  // Workspace
  COMPLIANCE_WORKSPACE_READ: "COMPLIANCE_WORKSPACE_READ",
  COMPLIANCE_WORKSPACE_CREATE: "COMPLIANCE_WORKSPACE_CREATE",
  COMPLIANCE_WORKSPACE_UPDATE: "COMPLIANCE_WORKSPACE_UPDATE",
  COMPLIANCE_WORKSPACE_ACTIVATE: "COMPLIANCE_WORKSPACE_ACTIVATE",

  // Evidence Vault
  COMPLIANCE_EVIDENCE_READ: "COMPLIANCE_EVIDENCE_READ",
  COMPLIANCE_EVIDENCE_UPLOAD: "COMPLIANCE_EVIDENCE_UPLOAD",
  COMPLIANCE_EVIDENCE_LINK: "COMPLIANCE_EVIDENCE_LINK",

  // Approvals (maker-checker)
  COMPLIANCE_APPROVAL_READ: "COMPLIANCE_APPROVAL_READ",
  COMPLIANCE_APPROVAL_SUBMIT: "COMPLIANCE_APPROVAL_SUBMIT",
  COMPLIANCE_APPROVAL_DECIDE: "COMPLIANCE_APPROVAL_DECIDE",

  // ABDM
  COMPLIANCE_ABDM_CONFIG: "COMPLIANCE_ABDM_CONFIG",
  COMPLIANCE_ABDM_HFR_UPDATE: "COMPLIANCE_ABDM_HFR_UPDATE",
  COMPLIANCE_ABDM_HPR_UPDATE: "COMPLIANCE_ABDM_HPR_UPDATE",

  // Government Schemes
  COMPLIANCE_SCHEME_EMPANEL: "COMPLIANCE_SCHEME_EMPANEL",
  COMPLIANCE_SCHEME_RATECARD_CREATE: "COMPLIANCE_SCHEME_RATECARD_CREATE",
  COMPLIANCE_SCHEME_RATECARD_FREEZE: "COMPLIANCE_SCHEME_RATECARD_FREEZE",
  COMPLIANCE_SCHEME_MAPPING: "COMPLIANCE_SCHEME_MAPPING",

  // NABH
  COMPLIANCE_NABH_TEMPLATE: "COMPLIANCE_NABH_TEMPLATE",
  COMPLIANCE_NABH_ITEM_UPDATE: "COMPLIANCE_NABH_ITEM_UPDATE",
  COMPLIANCE_NABH_ITEM_VERIFY: "COMPLIANCE_NABH_ITEM_VERIFY",
  COMPLIANCE_NABH_AUDIT: "COMPLIANCE_NABH_AUDIT",
  COMPLIANCE_NABH_FINDING: "COMPLIANCE_NABH_FINDING",
  COMPLIANCE_NABH_CAPA: "COMPLIANCE_NABH_CAPA",

  // Validator & Reports
  COMPLIANCE_VALIDATOR_RUN: "COMPLIANCE_VALIDATOR_RUN",
  COMPLIANCE_EXPORT: "COMPLIANCE_EXPORT",
  COMPLIANCE_AUDIT_LOG_READ: "COMPLIANCE_AUDIT_LOG_READ",
  COMPLIANCE_DASHBOARD_READ: "COMPLIANCE_DASHBOARD_READ",

  // ========== Blood Bank Module ==========

  // Facility Setup
  BB_FACILITY_READ: "BB_FACILITY_READ",
  BB_FACILITY_UPDATE: "BB_FACILITY_UPDATE",

  // Component Master
  BB_COMPONENT_READ: "BB_COMPONENT_READ",
  BB_COMPONENT_CREATE: "BB_COMPONENT_CREATE",
  BB_COMPONENT_UPDATE: "BB_COMPONENT_UPDATE",

  // Equipment
  BB_EQUIPMENT_READ: "BB_EQUIPMENT_READ",
  BB_EQUIPMENT_CREATE: "BB_EQUIPMENT_CREATE",
  BB_EQUIPMENT_UPDATE: "BB_EQUIPMENT_UPDATE",

  // Reagent
  BB_REAGENT_READ: "BB_REAGENT_READ",
  BB_REAGENT_CREATE: "BB_REAGENT_CREATE",
  BB_REAGENT_UPDATE: "BB_REAGENT_UPDATE",

  // Tariff
  BB_TARIFF_READ: "BB_TARIFF_READ",
  BB_TARIFF_UPDATE: "BB_TARIFF_UPDATE",

  // Donor Management
  BB_DONOR_READ: "BB_DONOR_READ",
  BB_DONOR_CREATE: "BB_DONOR_CREATE",
  BB_DONOR_UPDATE: "BB_DONOR_UPDATE",
  BB_DONOR_DEFER: "BB_DONOR_DEFER",

  // Blood Collection
  BB_COLLECTION_READ: "BB_COLLECTION_READ",
  BB_COLLECTION_CREATE: "BB_COLLECTION_CREATE",
  BB_COLLECTION_UPDATE: "BB_COLLECTION_UPDATE",

  // Testing & Screening
  BB_TESTING_READ: "BB_TESTING_READ",
  BB_TESTING_CREATE: "BB_TESTING_CREATE",
  BB_TESTING_VERIFY: "BB_TESTING_VERIFY",

  // Inventory
  BB_INVENTORY_READ: "BB_INVENTORY_READ",
  BB_INVENTORY_UPDATE: "BB_INVENTORY_UPDATE",
  BB_INVENTORY_DISCARD: "BB_INVENTORY_DISCARD",
  BB_INVENTORY_TRANSFER: "BB_INVENTORY_TRANSFER",

  // Blood Request
  BB_REQUEST_READ: "BB_REQUEST_READ",
  BB_REQUEST_CREATE: "BB_REQUEST_CREATE",
  BB_REQUEST_UPDATE: "BB_REQUEST_UPDATE",

  // Cross-Match
  BB_CROSSMATCH_READ: "BB_CROSSMATCH_READ",
  BB_CROSSMATCH_CREATE: "BB_CROSSMATCH_CREATE",
  BB_CROSSMATCH_VERIFY: "BB_CROSSMATCH_VERIFY",

  // Blood Issue
  BB_ISSUE_READ: "BB_ISSUE_READ",
  BB_ISSUE_CREATE: "BB_ISSUE_CREATE",
  BB_ISSUE_RETURN: "BB_ISSUE_RETURN",

  // Transfusion
  BB_TRANSFUSION_READ: "BB_TRANSFUSION_READ",
  BB_TRANSFUSION_CREATE: "BB_TRANSFUSION_CREATE",
  BB_TRANSFUSION_REACTION: "BB_TRANSFUSION_REACTION",

  // MTP
  BB_MTP_ACTIVATE: "BB_MTP_ACTIVATE",
  BB_MTP_READ: "BB_MTP_READ",

  // Quality Control
  BB_QC_READ: "BB_QC_READ",
  BB_QC_CREATE: "BB_QC_CREATE",

  // Reports
  BB_REPORT_READ: "BB_REPORT_READ",
  BB_REPORT_EXPORT: "BB_REPORT_EXPORT",

  // Donation Camps
  BB_CAMP_READ: "BB_CAMP_READ",
  BB_CAMP_CREATE: "BB_CAMP_CREATE",
  BB_CAMP_UPDATE: "BB_CAMP_UPDATE",

  // MSBOS
  BB_MSBOS_READ: "BB_MSBOS_READ",
  BB_MSBOS_UPDATE: "BB_MSBOS_UPDATE",

  // Audit
  BB_AUDIT_READ: "BB_AUDIT_READ",
} as const;

export const ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  CORPORATE_ADMIN: "CORPORATE_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  IT_ADMIN: "IT_ADMIN",
  // HR directory admin (typically BRANCH-scoped or GLOBAL depending on deployment)
  HR_ADMIN: "HR_ADMIN",
} as const;

