export const PERM = {
  IAM_USER_READ: "IAM_USER_READ",
  IAM_USER_CREATE: "IAM_USER_CREATE",
  IAM_USER_UPDATE: "IAM_USER_UPDATE",
  IAM_USER_RESET_PASSWORD: "IAM_USER_RESET_PASSWORD",
  IAM_PERMISSION_CREATE: "IAM_PERMISSION_CREATE",
  IAM_ROLE_READ: "IAM_ROLE_READ",
  IAM_PERMISSION_READ: "IAM_PERMISSION_READ",
  IAM_AUDIT_READ: "IAM_AUDIT_READ",
  IAM_ROLE_CREATE: "IAM_ROLE_CREATE",
  IAM_ROLE_UPDATE: "IAM_ROLE_UPDATE",
  
} as const;

export const ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  IT_ADMIN: "IT_ADMIN",
} as const;
